spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    master:
      driverClassName: com.mysql.cj.jdbc.Driver
      jdbcUrl: jdbc:mysql://localhost:3306/ecommerce?serverTimezone=UTC
      username: root
      password: root
    slave:
      driverClassName: com.mysql.cj.jdbc.Driver
      jdbcUrl: jdbc:mysql://localhost:3306/test?serverTimezone=UTC
      username: root
      password: root

